#!/usr/bin/env python

import ConfigParser
import requests
import getpass
import sys
import datetime

configFilePath = r'flexurio_config'

class flexurio():
    def __init__(self):
        configParser = ConfigParser.RawConfigParser()
        configParser.read(configFilePath)
        self.user = configParser.get('flx-config', 'id')
        self.password = configParser.get('flx-config', 'token')
        self.server = configParser.get('flx-config', 'server')

    def login(self):
        print ""
        print "Flexurio Auth, Don't have an account? Sign up at flexurio.com "
        print ""
        print ""
        username = raw_input("username: ")
        password = getpass.getpass()
        print ""
        r = requests.post(self.server, data={'username':username, 'password':password}).json()

        if r['status'] == "success":
            print "Setting up local config"
            userid =  r['data']['userId']
            authToken =  r['data']['authToken']
            configParser = ConfigParser.RawConfigParser()
            configParser.read(configFilePath)
            configParser.set('flx-config', 'id', userid)
            configParser.set('flx-config', 'token', authToken)
            with open(configFilePath, 'w') as configfile:
                configParser.write(configfile)
            print "Status : {0} at {1}".format(r['status'], datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        else:
            print "Status : {0} ==> {1} at {2}".format(r['status'], r['message'], datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

if sys.argv[1] == "login":
    try:
        configFilePath = sys.argv[2]
        Flexurio = flexurio()
        Flexurio.login()
    except KeyboardInterrupt:
        print ""
        print "Canceled by user"
if sys.argv[1] == "serverinit":
    try:
        configFilePath = sys.argv[2]
        Flexurio = flexurio()
        Flexurio.login()
    except KeyboardInterrupt:
        print "Canceled by user"
else:
    print "Thanks Bro, Jayalah Indonesia"
