#!/bin/bash
echo " ----------------------------------------------------------------------------------"
echo " |                                     INSTALLER                                  |"
echo " |     ___________     __________    _______    ___________     __    ______      |"
echo " |    |   ______  |   |   ____   \  /  ___  |  |  ___   _  \   |  |  /  __  \     |"
echo " |    |  |__   |  |   |  |__   \  \/  /  |  |  |  | |  |_)  |  |  | |  |  |  |    |"
echo " |    |   __|  |  |   |   __|   >    <   |  |  |  | |      /   |  | |  |  |  |    |"
echo " |    |  |     |   ----  |____ /  /\  \  |   --   | |  |\  \   |  | |   --   |    |"
echo " |    |__|     |_________________/  \__\ |_______/  |__| \__\  |__|  \______/     |"
echo " |                                                                                |"
echo " ----------------------------------------------------------------------------------"
echo ""

function progress-bar() {
  local duration=${1}

  already_done() { for ((done=0; done<elapsed; done=done+1)); do printf "▇"; done }
  remaining() { for ((remain=elapsed; remain<duration; remain=remain+1)); do printf " "; done }
  percentage() { printf "| %s%%" $(( ((elapsed)*100)/(duration)*100/100 )); }
  clean_line() { printf "\r"; }

  for (( elapsed=1; elapsed<=duration; elapsed=elapsed+1 )); do
      already_done; remaining; percentage
      sleep 1
      clean_line
  done
  clean_line
}

UNAME=$(uname)
if [ "$UNAME" ">" "MINGW" -a "$UNAME" "<" "MINGX" ] ; then
    echo "Sorry, flexurio on Windows not ready"
    exit
fi
if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
    echo "Sorry, this OS is not supported yet via this installer."
    echo "For more details on supported platforms, see https://www.flexurio.com"
    exit
fi

if [ "$1" == "-meteor" ] || [ "$1" == "-all" ]; then
    curl https://install.meteor.com/ | sh
    echo ""
    echo "Installation Meteor Complete."
    echo ""
    chmod -R +xrw ~/.meteor
elif [ "$1" == "-pip" ] || [ "$1" == "-all" ]; then
    if [ "$UNAME" == "Linux" ] ; then
        apt-get install python-pip
    fi
    if [ "$UNAME" == "Darwin" ] ; then
        curl https://bootstrap.pypa.io/get-pip.py | python
    fi
    pip install ConfigParser
    pip install requests
    echo ""
    echo "Installation Python PIP Complete."
    echo ""
elif [ "$1" == "-rn" ] || [ "$1" == "-all" ]; then
    npm install -g react-native-cli
    echo ""
    echo "Installation React-Native Complete."
    echo ""
elif [ "$1" == "-flx" ] || [ "$1" == "-all" ]; then
    if [ $(id -u) != 0 ]; then
         echo "You're not root"
         echo "Root user need to install Flexurio. Please use sudo "
         exit
    fi

    progress 20
    mkdir -p ~/.flexurio/
    cp -R flexurio_config ~/.flexurio/
    cp -R flexurio_portal ~/.flexurio/

    progress 50
    sleep 1

    sudo cp -R flexurio_theme_bootstrap ~/.flexurio/flexurio_theme_bootstrap
    sudo chmod +x ~/.flexurio/flexurio_theme_bootstrap

    cp -R flexurio_theme_materialize ~/.flexurio/flexurio_theme_materialize
    sudo chmod +x ~/.flexurio/flexurio_theme_materialize

    sudo cp -R flexurio ~/.flexurio/flexurio
    sudo rm -R /usr/local/bin/flexurio
    sudo ln -s ~/.flexurio/flexurio /usr/local/bin/flexurio
    sudo chmod +x /usr/local/bin/flexurio
    sudo chmod +x ~/.flexurio/flexurio

    echo ""
    echo "Please wait a moment, open access to meteors, mongodb, react, etc. Do not close or cancel this screen"
    echo ""
    progress 60
    sleep 1

    sudo chmod -R +xrw ~/.meteor

    progress 80
    sleep 1

    rm flexurio
    rm flexurio_portal
    rm flexurio_config
    rm flexurio_theme_bootstrap
    rm flexurio_theme_materialize
    rm install
    echo ""
    echo "Installation Flexurio Complete."
    echo ""
    progress 100
    sleep 1
else
    echo ""
    echo " Please input what you want install."
    echo " -meteor                    Install Meteor.JS"
    echo " -pip                       Install Python PIP"
    echo " -rn                        Install React-Native"
    echo ""
    echo " -flx                       Install FLEXURIO"
    echo " -all                       Install All packages that need on FLEXURIO"
    echo ""
fi
exit 0
